@TutorApi_HostAddress = http://192.168.2.103:5252

### Register a new user
POST {{TutorApi_HostAddress}}/account/register
Content-Type: application/json
Accept: application/json

{
  "email": "user@example.com",
  "password": "P@ssword1"
}
###

### Request password reset link
POST {{TutorApi_HostAddress}}/account/forgotPassword
Content-Type: application/json
Accept: application/json

{
  "email": "user@example.com"
}
###

### Reset password
POST {{TutorApi_HostAddress}}/account/resetPassword
Content-Type: application/json
Accept: application/json

{
  "email": "user@example.com",
  "token": "paste-token-from-reset-link",
  "newPassword": "NewP@ssword1"
}
###

### Login
POST {{TutorApi_HostAddress}}/account/login
Content-Type: application/json
Accept: application/json

{
  "email": "user@example.com",
  "password": "P@ssword1"
}
###
