@TutorApi_HostAddress = http://192.168.2.103:5252

### Create a new subscription for the user
POST {{TutorApi_HostAddress}}/subscription/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUdXRvckFwaTtUdXRvckFwaUFwcCIsImlzcyI6IlR1dG9yQXBpIiwiZXhwIjoxODgyNTY3Nzk4LCJpYXQiOjE3NjI1Njc3OTgsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA5LzA5L2lkZW50aXR5L2NsYWltcy9pZCI6ImFiZGNiMGFlLTkwZTMtNDg5Yy1hNTY3LWE3OGIyYzVjZTkyNiIsIm5iZiI6MTc2MjU2Nzc5OH0.v6jCWsNTJn8nfhSVYbr6g8YPnQCS7Lh_OMkYh2HYb-g
Accept: application/json
{
  "userId": "abdcb0ae-90e3-489c-a567-a78b2c5ce926",
  "subscriptionTypeId": "Basic"
}
###

### Get Subscription Groups
GET {{TutorApi_HostAddress}}/subscription/getSubscriptionGroups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUdXRvckFwaTtUdXRvckFwaUFwcCIsImlzcyI6IlR1dG9yQXBpIiwiZXhwIjoxODgyNTY3Nzk4LCJpYXQiOjE3NjI1Njc3OTgsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA5LzA5L2lkZW50aXR5L2NsYWltcy9pZCI6ImFiZGNiMGFlLTkwZTMtNDg5Yy1hNTY3LWE3OGIyYzVjZTkyNiIsIm5iZiI6MTc2MjU2Nzc5OH0.v6jCWsNTJn8nfhSVYbr6g8YPnQCS7Lh_OMkYh2HYb-g
###
