@TutorApi_HostAddress = http://192.168.2.103:5252

### Create a new subscription for the user
POST {{TutorApi_HostAddress}}/subscription/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUdXRvckFwaTtUdXRvckFwaUFwcCIsImlzcyI6IlR1dG9yQXBpIiwiZXhwIjoxODgyNjY1NzA4LCJpYXQiOjE3NjI2NjU3MDgsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA5LzA5L2lkZW50aXR5L2NsYWltcy9pZCI6IjQ3YzE0MzM5LWM3YjMtNDdjNy04MmQ1LWZlMTlhZGRjNTQyYyIsIm5iZiI6MTc2MjY2NTcwOH0.c-Av5izBAQEdko5B7nlihkOiId1ujQPJv5KfDZFD3Gc
Accept: application/json
{
  "userId": "47c14339-c7b3-47c7-82d5-fe19addc542c",
  "subscriptionTypeId": "Basic"
}
###

### Get Subscription Groups
GET {{TutorApi_HostAddress}}/subscription/getSubscriptionGroups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUdXRvckFwaTtUdXRvckFwaUFwcCIsImlzcyI6IlR1dG9yQXBpIiwiZXhwIjoxODgyNjY1NzA4LCJpYXQiOjE3NjI2NjU3MDgsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA5LzA5L2lkZW50aXR5L2NsYWltcy9pZCI6IjQ3YzE0MzM5LWM3YjMtNDdjNy04MmQ1LWZlMTlhZGRjNTQyYyIsIm5iZiI6MTc2MjY2NTcwOH0.c-Av5izBAQEdko5B7nlihkOiId1ujQPJv5KfDZFD3Gc
###
